### PR TITLE
Added my section:Aditi Bendre

### PR DESCRIPTION
**Pull request by AditiBendre**
Hii, i have added my section to the page.

### CODE REVIEW

**Comment by AditiBendre** [comment]
Do let me know if any changes are required.

**Review by MarkusEicher — COMMENTED** [review]
Hi folks. That looks fine. Well done.

**Comment by vansh-goel** [comment]
Great work Aditi! Accepting your PR rn.

**Comment by AditiBendre** [comment]
Thank you😊

**Pull request merged**
