### PR TITLE
🛠Created cards, fixed navigation bar to top and added my description too.

### PR DESCRIPTION
**Pull request by Sreejit-Sengupto**
## Closes  ISSUE: improve website ui #201 
Created cards for everybody's description section, fixed the navigation bar to top such that it remains fixed at a position even on scrolling. Also added my description section.

Screenshot (48)

### CODE REVIEW

**Review by Ezekiel8807 — CHANGES_REQUESTED** [review]
**Requested changes**

- add padding to the header 
- reduce the shadow effect on card
- add transition effect to card

**Comment by Sreejit-Sengupto** [comment]
> **Requested changes**
> 
> * add padding to the header
> * reduce the shadow effect on card
> * add transition effect to card

Sure! Can you please suggest what sort of transition to add?

**Comment by Ezekiel8807** [comment]
anyone that suit well is ok

**Comment by Sreejit-Sengupto** [comment]
Okay I will do it ASAP!

**Comment by Sreejit-Sengupto** [comment]
Please have a look!
Here is the screenshot as well
Screenshot (57)

**Review by vansh-goel — APPROVED** [review]
Looks great! Merging now

**Pull request merged**
