### PR TITLE
Added LinkedIn Icon 

### PR DESCRIPTION
**Pull request by ShivamPathak99**
Added LinkedIn Class and Icon

### CODE REVIEW

**Comment by ShivamPathak99** [comment]
Added my name and LinkedIn Logo, been stuck in a conflict for long.

**Comment by vansh-goel** [comment]
> Added my name and LinkedIn Logo, been stuck in a conflict for long.

It shows conflict because the code was updated due to merging other pull requests, try to make your changes again in the latest code

**Comment by ShivamPathak99** [comment]
This pull request is conflict free now .
Please consider it for hacktoberfest.

**Comment by vansh-goel** [comment]
Great work! Merging now

**Pull request merged**
